### ISSUE TITLE
Push to Heroku Failed

### ISSUE THREAD

**Issue by thysmichels** [jamesward/hello-java-spring-force_dot_com#1]
Failed to execute goal on project hello-java-spring-force_dot_com: Could not resolve dependencies for project com.example:hello-java-spring-force_dot_com:war:0.0.1-SNAPSHOT: Failed to collect dependencies for [com.github.twitter:bootstrap:jar:2.0.3 (compile), javax.servlet:javax.servlet-api:jar:3.0.1 (provided), org.springframework:spring-webmvc:jar:3.1.1.RELEASE (compile), taglibs:standard:jar:1.1.2 (compile), javax.servlet:jstl:jar:1.2 (compile), com.force.api:force-rest-api:jar:0.0.18 (compile), com.force.sdk:force-oauth:jar:22.0.8-BETA (compile), com.force.sdk:force-springsecurity:jar:22.0.8-BETA (compile), com.github.jsimone:webapp-runner:jar:7.0.22.3 (provided)]: No versions available for org.codehaus.jackson:jackson-mapper-asl:jar:[1.9.1,1.9.7] within specified range -> [Help 1]

**Comment by jamesward** [comment]
I've just pushed a change that forces the `jackson-mapper-asl` version number.  Not sure why this stopped working.  But let me know if you still have issues.
