### ISSUE TITLE
Make endpoint="http://login.salesforce.com" configurable

### ISSUE THREAD

**Issue by thysmichels** [jamesward/hello-java-spring-force_dot_com#2]
Hi James,

Need some help on configuring the aouthInfo endpoint: 

``` html
<fss:oauth logout-url="/logout" default-logout-success="/" store-data-in-session="true">
        <fss:oauthInfo endpoint="http://login.salesforce.com"
                       oauth-key="#{systemEnvironment['OAUTH_CLIENT_KEY']}"
                       oauth-secret="#{systemEnvironment['OAUTH_CLIENT_SECRET']}"/>
    </fss:oauth>"
```

I want to make the endpoint to be configurable during login where I can popup a option to select environment. So the endpoint needs to switch between:
endpoint="http://login.salesforce.com"
endpoint="http://sandbox.salesforce.com"  

Any suggestions on how I can do this?

**Comment by jamesward** [comment]
That is a good question.  I'm sure there is some way to set that programmatically but it has been a while since I played with these APIs.  Sorry I'm not more helpful.

**Comment by thysmichels** [comment]
Np :+1:
